# Generated by Django 3.1.5 on 2021-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210602_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='unique_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
