# Generated by Django 3.1.5 on 2021-06-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_userdetail_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='unique_id',
            field=models.BigIntegerField(max_length=15, null=True),
        ),
    ]
