# Generated by Django 3.1.5 on 2021-06-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20210610_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='unique_id',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='webdetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.userdetail'),
        ),
    ]
