# Generated by Django 3.1.5 on 2021-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20210610_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='unique_id',
            field=models.IntegerField(default=719751553763789, max_length=15, null=True),
        ),
    ]
