# Generated by Django 3.1.5 on 2021-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20210610_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='unique_id',
            field=models.IntegerField(default=570654644098973, null=True),
        ),
    ]
