# Generated by Django 3.1.5 on 2021-06-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20210610_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='unique_id',
        ),
    ]
