# Generated by Django 3.1.5 on 2021-06-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_delete_webdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='middle_name',
        ),
    ]
